### ISSUE TITLE
puppet4 support in lib/facter/sssd.rb

### ISSUE THREAD

**Issue by fschaer** [theforeman/puppet-foreman#381] opened 2015-12-08 13:28 UTC
Hi,

It appears that the puppetserver (not master...) is unhappy with the bundled ruby facts.
When I run it on a CentOS7 VM with the puppetserver package installed from puppet PCL repository, I get : 

```
Error: Facter: error while resolving custom facts in /puppet/code/envs/dev/puppet/foreman/lib/facter/sssd.rb: cannot load such file -- util/sssd
```

If I edit this sssd.rb file like this : 

```` 
--- lib/facter/sssd.rb.old      2015-12-08 14:06:41.000000000 +0100
+++ lib/facter/sssd.rb  2015-12-08 14:25:30.000000000 +0100
@@ -1,4 +1,8 @@
 begin
+  #puppetserver/puppet4
+  require_relative 'util/sssd'
+rescue NoMethodError
+  #puppet master/puppet3
   require 'facter/util/sssd'
 rescue LoadError
   # Puppet 2 compatibility, facter/ dir is the load path, not lib/
```

Then the puppet apply is not erroring out anymore. 

I think the NoMethodError rescue is required, because require_relative does not seem to work on a an "old" puppet3.8 host.
Since I really am not a ruby developper, I prefer submitting an issue with awork around than a pull requests (+ tests that I don't know how to write (yet)), hope you don't mind...

Regards

**Comment by mmoll** [comment] 2015-12-12 22:50
@domcleal @stbenjam could you have a look?

**Comment by domcleal** [comment] 2015-12-14 08:11
Not sure why the original util/sssd wouldn't load, but the reason for `require_relative` may be that it's Ruby 1.9+ only so wouldn't work on 1.8.7 platforms.

Perhaps we could just use `require File.expand_path('../util/sssd', _FILE__)` to require it by the full path.

**Comment by mmoll** [comment] 2016-02-11 16:58
@fschaer could you check if the way that @domcleal suggested works on Puppet 4 and 3.8 and if yes, update this PR?

**Comment by fschaer** [comment] 2016-02-12 08:19
@mmoll sure, I'll check

**Comment by fschaer** [comment] 2016-02-12 08:34
Tested and working... but I do not seem to be able to reproduce the issue with the original require... ??
May I suggest this is closed as invalid ? (unless others are facing this ?)
Regards

**Comment by mmoll** [comment] 2016-02-12 09:47
@fschaer maybe you updated puppet(server) in the meanwhile and the behaviour is different now?

**Comment by fschaer** [comment] 2016-02-12 10:04
I upgraded many things indeed, and after those upgrades I reinstalled the VM to be sure I could bootstrap a new puppetserver with my puppet modules...
Well, at least I can say that it seems ok now with puppetserver-2.2.1-1.el7.noarch...

**Comment by ekohl** [comment] 2016-02-17 10:15
Given we can't reproduce this anymore I'm closing this.

**Closed by ekohl** 2016-02-17 10:15 UTC
Labels: puppet-4
